transactionclassification:
  configurations:
    - description: "NATIONWIDE"
      tag: "Committed"
      category: "Insurance"
    - description: "ONLINE CREDIT CA"
      tag: "Account Transfer"
    - description: "McDonald's"
      tag: "Eating Out"
      category: "Fast Food"